version: '3'
services:
  redis:
    restart: always
    image: redis:alpine
    ports:
      - 6379
  web:
      build: ./
      image: gaetancollaud/blockchain-node
      ports:
        - 8080
      links:
        - redis
      environment:
        - JAVA_OPTS=-Dspring.profiles.active=dev
      labels:
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:blockain.collaud.me"
        - "traefik.docker.network=traefik"
        - "traefik.frontend.priority=10"
        - "traefik.port=8080"
      networks:
        - traefik

networks:
  traefik:
    external: true
